/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostilelands.views;

import hostilelands.Game;
import hostilelands.events.GameEventDialog;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.swing.*;
import javax.swing.border.*;

/**
 *
 * @author Elscouta
 */
public class MainWindow extends javax.swing.JFrame 
{
    Game game;
    
    CurrentTimeLabel currentTimeLabel;
    MapView mapView;
    DialogLayer dialogLayer;
    CombatLayer combatLayer;
    UILayer uiLayer;
    
    /**
     * Creates new form MainWindow
     */
    private MainWindow(Game game) throws java.io.IOException 
    {
        this.game = game;
        initComponents();
        
        topBar.setBorder(game.getUIMgr().getBorder());
        characterBar.setBorder(game.getUIMgr().getBorder());
        mainPane.addComponentListener(new MainPaneResizeListener());
        
        mapView = MapView.create(game.getWorld(), game.getParty());
        mapView.setSize(mainPane.getSize());
        mainPane.add(mapView, new Integer(0));

        combatLayer = CombatLayer.create(game, game.getCombatModel());
        combatLayer.setSize(mainPane.getSize());
        mainPane.add(combatLayer, new Integer(1));
        
        uiLayer = UILayer.create(game.getUIMgr());
        uiLayer.setSize(mainPane.getSize());
        mainPane.add(uiLayer, new Integer(2));
        
        dialogLayer = DialogLayer.create(game, game.getUIMgr());
        dialogLayer.setSize(mainPane.getSize());
        mainPane.add(dialogLayer, new Integer(3));
                
        currentTimeLabel = new CurrentTimeLabel(game.getTime());
        topBar.add(currentTimeLabel, BorderLayout.LINE_END);
        
        PersonListView pview = PersonListView.createViewOf(game.getParty(), game.getUIMgr());
        characterBar.add(pview, BorderLayout.LINE_START);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        characterBar = new javax.swing.JPanel();
        topBar = new javax.swing.JPanel();
        mainPane = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 800));

        characterBar.setFocusable(false);
        characterBar.setMinimumSize(new java.awt.Dimension(0, 140));
        characterBar.setPreferredSize(new java.awt.Dimension(1000, 150));
        characterBar.setLayout(new java.awt.BorderLayout());
        getContentPane().add(characterBar, java.awt.BorderLayout.SOUTH);

        topBar.setPreferredSize(new java.awt.Dimension(1000, 25));
        topBar.setLayout(new java.awt.BorderLayout());
        getContentPane().add(topBar, java.awt.BorderLayout.PAGE_START);

        mainPane.setBackground(new java.awt.Color(80, 80, 80));
        mainPane.setPreferredSize(new java.awt.Dimension(1000, 650));
        getContentPane().add(mainPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     */
    public static void create(Game game, UIMgr uiMgr) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try 
                {
                    MainWindow w = new MainWindow(game);
                    w.setSize(1050, 800);

                    uiMgr.onMainWindowLoad(w);
                    game.fireEvent(new GameEventDialog("Welcome!", "This is a beautiful game. You can trust me, I'm a doctor."));

                    w.setVisible(true);
                } 
                catch (Exception e)
                {
                    e.printStackTrace();
                    System.exit(1);
                }
            }
        });
    }

    private class MainPaneResizeListener extends ComponentAdapter
    {
        public void componentResized(ComponentEvent e)
        {
            mapView.setSize(mainPane.getSize());
            uiLayer.setSize(mainPane.getSize());
            dialogLayer.setSize(mainPane.getSize());
            combatLayer.setSize(mainPane.getSize());            
        }
    }
    
    public UILayer getUILayer()
    {
        return uiLayer;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel characterBar;
    private javax.swing.JLayeredPane mainPane;
    private javax.swing.JPanel topBar;
    // End of variables declaration//GEN-END:variables
}
